const LOGIN = {
  LOAD: 'LOGIN_LOAD',
  LOAD_SUCCESS: 'LOGIN_LOAD_SUCCESS',
  LOAD_FAIL: 'LOGIN_LOAD_FAIL',
};

const REGISTER = {
  REQUEST: 'REGISTER_REQUEST',
  REQUEST_SUCCESS: 'REGISTER_REQUEST_SUCCESS',
  REQUEST_FAIL: 'REGISTER_REQUEST_FAIL',
};

const LOADING = {
  SHOW_LOADING: 'GLOBAL_SHOW_LOADING',
  HIDE_LOADING: 'GLOBAL_HIDE_LOADING',
};

const MESSAGE = {
  SHOW_MESSAGE: 'GLOBAL_SHOW_MESSAGE',
  HIDE_MESSAGE: 'GLOBAL_HIDE_MESSAGE',
};

const LOGOUT = {
  SUBMIT: 'LOGOUT_SUBMIT',
};

const INFO = {
  LOAD_INFO: 'USER_INFO_LOAD',
  SUCCESS_INFO: 'USER_INFO_SUCCESS',
  FAILED_INFO: 'USER_INFO_FAILED',
};

const CHANGE_PASSWORD = {
  CHANGE_PASSWORD_LOAD: 'CHANGE_PASSWORD_REQUEST',
  CHANGE_PASSWORD_REFRESH: 'REFRESH_CHANGE_PASSWORD',
  CHANGE_PASSWORD_SUCCESS: 'SUCCESS_CHANGE_PASSWORD',
  CHANGE_PASSWORD_FAILED: 'FAILED_CHANGE_PASSWORD',
};

const GET_GROUP_LIST = {
  REQUEST_GROUP_LIST: 'LOAD_GROUP_LIST',
  SUCCESS_GROUP_LIST: 'SUCCESS_GROUP_LIST',
  FAILED_GROUP_LIST: 'FAILED_GROUP_LIST',
};

const GET_TOPIC_LIST = {
  REQUEST_TOPIC_LIST: 'TOPIC_LIST_REQUEST',
  TOPIC_LIST_SUCCESS: 'SUCCESS_TOPIC_LIST',
  FAILED_TOPIC_LIST: 'FAILED_TOPIC_LIST',
};

const GET_POST_LIST = {
  REQUEST_POST_LIST: 'POST_LIST_REQUEST',
  POST_LIST_SUCCESS: 'SUCCESS_POST_LIST',
  FAILED_POST_LIST: 'FAILED_POST_LIST',
};

const REQUEST_POST = {
  LOAD_POST: 'POST_REQUEST',
  POST_SUCCESS: 'SUCCESS_POST',
  FAILED_POST: 'FAILED_POST',
};

const COMMENT_REQUEST = {
  COMMENT_POST_REQUEST: 'COMMENT_REQUEST',
  COMMENT_POST_SUCCESS: 'COMMENT_SUCCESS',
  COMMENT_POST_FAILED: 'COMMENT_FAILED',
};

export {
  LOGIN,
  REGISTER,
  LOADING,
  MESSAGE,
  LOGOUT,
  INFO,
  CHANGE_PASSWORD,
  GET_GROUP_LIST,
  GET_TOPIC_LIST,
  GET_POST_LIST,
  REQUEST_POST,
  COMMENT_REQUEST,
};
