const LOGIN = {
  LOAD: 'LOGIN_LOAD',
  LOAD_SUCCESS: 'LOGIN_LOAD_SUCCESS',
  LOAD_FAIL: 'LOGIN_LOAD_FAIL',
};

const REGISTER = {
  REQUEST: 'REGISTER_REQUEST',
  REQUEST_SUCCESS: 'REGISTER_REQUEST_SUCCESS',
  REQUEST_FAIL: 'REGISTER_REQUEST_FAIL',
};

const LOADING = {
  SHOW_LOADING: 'GLOBAL_SHOW_LOADING',
  HIDE_LOADING: 'GLOBAL_HIDE_LOADING',
};

const MESSAGE = {
  SHOW_MESSAGE: 'GLOBAL_SHOW_MESSAGE',
  HIDE_MESSAGE: 'GLOBAL_HIDE_MESSAGE',
};

const LOGOUT = {
  SUBMIT: 'LOGOUT_SUBMIT',
};

const INFO = {
  LOAD_INFO: 'USER_INFO_LOAD',
  SUCCESS_INFO: 'USER_INFO_SUCCESS',
  FAILED_INFO: 'USER_INFO_FAILED',
};

const CHANGE_PASSWORD = {
  CHANGE_PASSWORD_LOAD: 'CHANGE_PASSWORD_REQUEST',
  CHANGE_PASSWORD_REFRESH: 'REFRESH_CHANGE_PASSWORD',
  CHANGE_PASSWORD_SUCCESS: 'SUCCESS_CHANGE_PASSWORD',
  CHANGE_PASSWORD_FAILED: 'FAILED_CHANGE_PASSWORD',
};

export { LOGIN, REGISTER, LOADING, MESSAGE, LOGOUT, INFO, CHANGE_PASSWORD };
